import {zipSync,strToU8} from '../../public/data-core/vendor/fflate-0.8.3.js';
import {columnName} from '../../public/data-core/work/attendance-template.js';

export function attendanceFixture({students=20,capacity=students,orientation='landscape',offset=0,footer=false,formula=false,drawing=false,conditional=false,month=9,year=2026}={}) {
  const rows=[],start=4,first=3+offset,last=first+30,end=start+capacity-1;
  const cell=(c,r,value,style=0)=>`<c r="${columnName(c)}${r}" s="${style}"${typeof value==='number'?'':' t="inlineStr"'}>${typeof value==='number'?`<v>${value}</v>`:`<is><t>${value}</t></is>`}</c>`;
  rows.push(`<row r="1" ht="28" customHeight="1">${cell(1,1,`${year}년 ${month}월 SYNTHETIC 출석부`,3)}</row>`);
  for(const r of [2,3])rows.push(`<row r="${r}" ht="16" customHeight="1">${cell(1,r,r===2?'학생명':'',1)}${cell(2,r,r===2?'수업요일':'',1)}${Array.from({length:31},(_,i)=>cell(first+i,r,r===2?i+1:'일월화수목금토'[new Date(Date.UTC(year,month-1,i+1)).getUTCDay()],1)).join('')}</row>`);
  for(let i=0;i<capacity;i++){
    const r=start+i,days=i%2?'화목':'월수금';
    rows.push(`<row r="${r}" ht="15" customHeight="1">${cell(1,r,i<students?`SYNTHETIC_${String(i+1).padStart(3,'0')}`:'',1)}${cell(2,r,i<students?days:'',1)}${Array.from({length:31},(_,d)=>cell(first+d,r,d===0&&i===0?'✓':'',i<students&&days.includes('일월화수목금토'[new Date(Date.UTC(year,month-1,d+1)).getUTCDay()])?2:1)).join('')}</row>`);
  }
  if(footer)rows.push(`<row r="${end+1}" ht="18" customHeight="1">${cell(1,end+1,'SYNTHETIC FOOTER',1)}</row>`);
  const sheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:${columnName(last)}${end+(footer?1:0)}"/><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><cols><col min="1" max="1" width="18" customWidth="1"/><col min="2" max="2" width="10" customWidth="1"/><col min="${first}" max="${last}" width="2.4" customWidth="1"/></cols><sheetData>${rows.join('')}</sheetData><mergeCells count="${footer?2:1}"><mergeCell ref="A1:${columnName(last)}1"/>${footer?`<mergeCell ref="A${end+1}:${columnName(last)}${end+1}"/>`:''}</mergeCells>${conditional?'<conditionalFormatting sqref="C4:AG23"><cfRule type="expression" priority="1"><formula>TRUE</formula></cfRule></conditionalFormatting>':''}<printOptions horizontalCentered="1"/><pageMargins left="0.25" right="0.25" top="0.3" bottom="0.3" header="0.15" footer="0.15"/><pageSetup paperSize="9" orientation="${orientation}" fitToWidth="1" fitToHeight="1" scale="82" horizontalDpi="300" verticalDpi="300"/>${drawing?'<drawing r:id="rIdDrawing"/>':''}</worksheet>`;
  const entries={
    '[Content_Types].xml':`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`,
    '_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
    'xl/workbook.xml':`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView activeTab="0"/></bookViews><sheets><sheet name="출석부" sheetId="1" r:id="rId1"/><sheet name="보존" sheetId="2" r:id="rId2"/></sheets><definedNames><definedName name="_xlnm.Print_Area" localSheetId="0">'출석부'!$A$1:$${columnName(last)}$${end+(footer?1:0)}</definedName><definedName name="_xlnm.Print_Titles" localSheetId="0">'출석부'!$1:$3,'출석부'!$A:$B</definedName></definedNames><calcPr calcId="191029"/></workbook>`,
    'xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
    'xl/worksheets/sheet1.xml':sheet,
    'xl/worksheets/sheet2.xml':`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>UNCHANGED</t></is></c>${formula?'<c r="B1"><f>1+1</f><v>2</v></c>':''}</row></sheetData></worksheet>`,
    'xl/styles.xml':`<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="0.0"/></numFmts><fonts count="2"><font><sz val="9"/><name val="Arial"/><color rgb="FF222222"/></font><font><b/><sz val="16"/><name val="Arial"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFF2CC"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFDDEBF7"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/></border><border><left style="thin"><color rgb="FF555555"/></left><right style="thin"><color rgb="FF555555"/></right><top style="thin"><color rgb="FF555555"/></top><bottom style="thin"><color rgb="FF555555"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="0" fillId="0" borderId="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="2" borderId="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="3" borderId="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`,
    'docProps/custom.xml':'<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><property name="SYNTHETIC-preservation" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2"><vt:lpwstr>UNCHANGED</vt:lpwstr></property></Properties>'
  };
  return zipSync(Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,strToU8(v)])),{level:6});
}
